/** Copyright (C) 2022  Frieder Pankratz <frieder.pankratz@gmail.com> **/

#ifndef TRAACT_COMPONENT_BASIC_SRC_TRAACT_COMPONENT_VISION_VISIONGPUFUNCTIONS_CUH_
#define TRAACT_COMPONENT_BASIC_SRC_TRAACT_COMPONENT_VISION_VISIONGPUFUNCTIONS_CUH_

#include <cuda_runtime.h>

namespace traact::vision {

}


#endif //TRAACT_COMPONENT_BASIC_SRC_TRAACT_COMPONENT_VISION_VISIONGPUFUNCTIONS_CUH_
